version: '3.8'

services:
  backend:
    build: ./backend
    network_mode: "host"  # host 네트워크 사용
    restart: unless-stopped
    volumes:
      - ./backend/app:/app/app
      - ./backend/.env:/app/.env
      - ./logs:/app/logs  # 로그 디렉토리를 호스트에 마운트
      - ./backend:/app/db_storage  # DB 파일 저장을 위한 호스트 디렉토리 마운트
    working_dir: /app
    env_file:
      - ./backend/.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --reload-exclude 'logs/*'

  frontend:
    build: ./frontend
    network_mode: "host"  # host 네트워크 사용
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    stdin_open: true
    tty: true
    depends_on:
      - backend

# networks 섹션 제거 (host 모드에서는 불필요)
